import { useEffect, useMemo, useState } from "react";
import {
  ArrowRight,
  BadgeCheck,
  Boxes,
  ClipboardCheck,
  Library,
  MapPin,
  Printer,
  ReceiptText,
  UploadCloud,
} from "lucide-react";
import { Link } from "react-router-dom";
import { getActiveMaterials } from "../api/materials";
import { useAuth } from "../context/AuthContext";

const WORKFLOW_STEPS = [
  {
    title: "Design",
    description: "Upload a model or start from a UniFab-hosted design.",
  },
  {
    title: "Quote",
    description: "Generate slicer-backed cost, time, and material estimates.",
  },
  {
    title: "Submit",
    description: "Create a request from a valid quote or cart draft.",
  },
  {
    title: "Pay",
    description: "Use the payment slip and verify the receipt in person.",
  },
  {
    title: "Track",
    description: "Follow the request timeline until completion.",
  },
];

const CAPABILITY_CARDS = [
  {
    number: "01",
    title: "Preview quotes before signing in",
    description:
      "Guests can upload supported models, choose print settings, and review slicer-based estimates before creating an account.",
    icon: UploadCloud,
  },
  {
    number: "02",
    title: "Move from quote to request with guardrails",
    description:
      "Verified clients submit only from successful quote snapshots, with Terms acceptance and final confirmation before review.",
    icon: ClipboardCheck,
  },
  {
    number: "03",
    title: "Browse designs with clear readiness",
    description:
      "UniFab separates Print Ready files, official lab designs, community submissions, and external references.",
    icon: Library,
  },
];

const LIBRARY_CARDS = [
  {
    label: "Print Ready",
    title: "Verified files",
    detail: "Instant quote is enabled only after FabLab file-level slicer review.",
  },
  {
    label: "UniFab Designs",
    title: "Official and community catalog",
    detail: "Approved hosted designs can be browsed, downloaded, saved, and reviewed.",
  },
  {
    label: "External Reference",
    title: "MyMiniFactory discovery",
    detail: "MMF entries stay external unless admins cache and verify printable files.",
  },
];

const SUPPORT_ITEMS = [
  "Backend-generated model snapshots open the 3D viewer only when needed.",
  "Admin pricing, materials, colors, and slicer profiles drive future quotes.",
  "Payment slips are generated by the backend and checked with physical receipts.",
];

const DEFAULT_MATERIAL_CHIPS = [
  "Backend materials",
  "Managed profiles",
  "Slicer diagnostics",
  "Quote readiness",
];

function getFirstName(name) {
  return String(name || "").trim().split(/\s+/)[0] || "";
}

export default function Home() {
  const { user, isAuthenticated } = useAuth();
  const [materials, setMaterials] = useState([]);
  const [materialStatus, setMaterialStatus] = useState("loading");
  const [mascotState, setMascotState] = useState("happy");

  useEffect(() => {
    let isMounted = true;

    async function loadMaterials() {
      try {
        const data = await getActiveMaterials();
        const activeMaterials = data.data?.materials || data.materials || [];

        if (!isMounted) return;

        setMaterials(activeMaterials);
        setMaterialStatus("ready");
      } catch {
        if (!isMounted) return;

        setMaterials([]);
        setMaterialStatus("fallback");
      }
    }

    loadMaterials();

    return () => {
      isMounted = false;
    };
  }, []);

  useEffect(() => {
    if (mascotState === "blank") return undefined;

    const timer = window.setTimeout(() => setMascotState("blank"), 1800);

    return () => window.clearTimeout(timer);
  }, [mascotState]);

  const materialChips = useMemo(() => {
    if (materials.length === 0) {
      return DEFAULT_MATERIAL_CHIPS;
    }

    return materials
      .slice(0, 6)
      .map(
        (material) =>
          material.displayName ||
          material.name ||
          material.materialKey ||
          "Material",
      );
  }, [materials]);

  const firstName = getFirstName(user?.name);
  const greeting = isAuthenticated
    ? `Welcome back${firstName ? `, ${firstName}` : ""}`
    : "Welcome to UniFab";

  return (
    <main className="unifab-home">
      <div className="unifab-home__texture" aria-hidden="true" />

      <section className="unifab-home__material-bar" aria-label="Quote support">
        <div className="unifab-home__shell unifab-home__material-inner">
          {materialChips.map((chip) => (
            <Link key={chip} to="/quote">
              {chip}
            </Link>
          ))}
        </div>
      </section>

      <section className="unifab-home__hero">
        <div className="unifab-home__shell">
          <div className="unifab-home__welcome">
            <span aria-hidden="true" />
            <h1>{greeting}</h1>
            <span
              className={`unifab-home__mascot is-${mascotState}`}
              aria-label="UniFab assistant mascot"
            >
              <img
                className="unifab-home__mascot-state unifab-home__mascot-state--happy"
                src="/assets/mascot/mascot-happy.svg"
                alt="UniFab assistant mascot"
              />
              <img
                className="unifab-home__mascot-state unifab-home__mascot-state--blank"
                src="/assets/mascot/mascot-blank.svg"
                alt=""
                aria-hidden="true"
              />
              <img
                className="unifab-home__mascot-state unifab-home__mascot-state--serious"
                src="/assets/mascot/mascot-serious.svg"
                alt=""
                aria-hidden="true"
              />
            </span>
            <span aria-hidden="true" />
          </div>

          <div className="unifab-home__hero-card">
            <div className="unifab-home__hero-copy">
              <p className="unifab-home__eyebrow">
                USTP-CDO Fabrication Laboratory
              </p>
              <h2>Get a slicer-backed 3D print quote</h2>
              <p>
                Upload a supported model, choose material settings, and review
                the quote before deciding whether to submit a print request.
              </p>
              <div className="unifab-home__hero-actions">
                <Link
                  className="unifab-home__button unifab-home__button--primary"
                  to="/quote"
                  onMouseEnter={() => setMascotState("happy")}
                  onFocus={() => setMascotState("happy")}
                >
                  Start a quote
                  <ArrowRight aria-hidden="true" />
                </Link>
                <Link
                  className="unifab-home__button unifab-home__button--secondary"
                  to="/designs"
                >
                  Browse designs
                </Link>
              </div>
            </div>

            <Link
              className="unifab-home__upload-zone"
              to="/quote"
              onMouseEnter={() => setMascotState("happy")}
              onFocus={() => setMascotState("happy")}
            >
              <span className="unifab-home__upload-icon" aria-hidden="true">
                <UploadCloud />
              </span>
              <strong>Upload for quote</strong>
              <span>
                The actual quote workflow runs on the backend with managed
                material, color, quality, infill, and quantity controls.
              </span>
            </Link>
          </div>

          <ol className="unifab-home__workflow" aria-label="UniFab workflow">
            {WORKFLOW_STEPS.map((step, index) => (
              <li key={step.title}>
                <span>{index + 1}</span>
                <strong>{step.title}</strong>
                <p>{step.description}</p>
              </li>
            ))}
          </ol>

          <div className="unifab-home__notice" role="note">
            <BadgeCheck aria-hidden="true" />
            <p>
              <strong>Guest quote preview stays open.</strong> Verified email
              access is required only when adding quotes to cart or submitting a
              print request for FabLab review.
            </p>
          </div>
        </div>
      </section>

      <section className="unifab-home__section unifab-home__shell">
        <div className="unifab-home__section-heading">
          <div>
            <p className="unifab-home__eyebrow">What UniFab supports</p>
            <h2>Campus fabrication without guesswork</h2>
          </div>
          <p>
            The public flow stays simple for students and faculty while the
            lab keeps control of quotes, files, profiles, and request status.
          </p>
        </div>

        <div className="unifab-home__overview-grid">
          {CAPABILITY_CARDS.map((card) => {
            const Icon = card.icon;

            return (
              <article className="unifab-home__overview-card" key={card.title}>
                <span>{card.number}</span>
                <Icon aria-hidden="true" />
                <h3>{card.title}</h3>
                <p>{card.description}</p>
              </article>
            );
          })}
        </div>
      </section>

      <section className="unifab-home__benefits unifab-home__shell">
        <div className="unifab-home__benefits-panel">
          <div>
            <p className="unifab-home__eyebrow">Operational guardrails</p>
            <h2>Designed around the FabLab service path</h2>
          </div>
          <div className="unifab-home__benefit-list">
            {SUPPORT_ITEMS.map((item) => (
              <p key={item}>{item}</p>
            ))}
          </div>
        </div>
      </section>

      <section className="unifab-home__section unifab-home__shell">
        <div className="unifab-home__section-heading">
          <div>
            <p className="unifab-home__eyebrow">Design Library</p>
            <h2>Readiness is visible before users quote</h2>
          </div>
          <Link to="/designs">Browse all designs</Link>
        </div>

        <div className="unifab-home__design-grid">
          {LIBRARY_CARDS.map((card, index) => (
            <article className="unifab-home__design-card" key={card.title}>
              <div className="unifab-home__design-visual" aria-hidden="true">
                {index === 0 ? <BadgeCheck /> : index === 1 ? <Boxes /> : <Library />}
              </div>
              <p>{card.label}</p>
              <h3>{card.title}</h3>
              <span>{card.detail}</span>
              <Link to="/designs">Open library</Link>
            </article>
          ))}
        </div>
      </section>

      <section className="unifab-home__start unifab-home__shell">
        <div className="unifab-home__start-panel">
          <div>
            <p className="unifab-home__eyebrow">Get started</p>
            <h2>Start with a quote. Submit when the details are ready.</h2>
          </div>
          <div className="unifab-home__start-actions">
            <Link className="unifab-home__action-card" to="/quote">
              <UploadCloud aria-hidden="true" />
              <strong>New quote</strong>
              <span>Upload STL, OBJ, or 3MF files for backend slicing.</span>
            </Link>
            <Link className="unifab-home__action-card" to="/requests">
              <ReceiptText aria-hidden="true" />
              <strong>Track requests</strong>
              <span>Review status, payment slips, and receipt verification.</span>
            </Link>
            <Link className="unifab-home__action-card" to="/printers">
              <Printer aria-hidden="true" />
              <strong>View printers</strong>
              <span>See public lab printer information without changing quotes.</span>
            </Link>
          </div>
        </div>
      </section>

      <section className="unifab-home__info unifab-home__shell">
        <div className="unifab-home__info-panel">
          <div>
            <p className="unifab-home__eyebrow">FabLab info</p>
            <h2>Visit the USTP-CDO FabLab</h2>
            <dl>
              <div>
                <dt>Hours</dt>
                <dd>Confirm the current service schedule before visiting.</dd>
              </div>
              <div>
                <dt>Location</dt>
                <dd>USTP-CDO campus fabrication laboratory.</dd>
              </div>
              <div>
                <dt>Support</dt>
                <dd>Quote review, payment slips, receipt checks, and request tracking.</dd>
              </div>
            </dl>
          </div>
          <div className="unifab-home__map-panel" aria-label="FabLab location map">
            <MapPin aria-hidden="true" />
          </div>
        </div>
      </section>

      <p className="sr-only" aria-live="polite">
        {materialStatus === "loading"
          ? "Loading active materials."
          : materialStatus === "ready"
            ? "Active material shortcuts loaded."
            : "Material shortcuts are showing general quote support links."}
      </p>
    </main>
  );
}
